[features]
seeds = false
skip-lint = false
[programs.localnet]
basic_swap = "7GFXgchPpNAaysNviqMjDFD9kE4YbW1DAEaVCMoRnTCU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ylgr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/basic_swap.json app/src/idl/basic_swap.json"
